substitutions:
  NAME: backyard_garden_hub
  PREFIX: Backyard Garden Hub
  WIFI_AP_SSID: ESP-BGBH
  REBOOT_TIMEOUT: 120min
  LOG_LEVEL: INFO
  MQTT_PREFIX: !secret MQTT_PREFIX
  UPDATE_INTERVAL: 10min

esphome:
  <<: !include partial/esphome_d1_mini.yaml

globals:
  - id: battery_min
    type: float
    initial_value: "100"
  - id: battery_max
    type: float
    initial_value: "-100"

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

i2c:

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  - name: $PREFIX ADC
    id: adc1v
    platform: adc
    pin: A0
    update_interval: $UPDATE_INTERVAL
    accuracy_decimals: 3

  - id: battery
    platform: template
    lambda: return id(adc1v).state * 21.797;
    update_interval: 1min

  - name: $PREFIX Battery
    id: battery_10min
    platform: template
    lambda: return id(battery).state;
    update_interval: 1min
    accuracy_decimals: 1
    unit_of_measurement: V
    icon: mdi:car-battery
    filters:
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10

  - name: $PREFIX Battery Min
    id: battery_min_sensor
    platform: template
    lambda: return id(battery_min);
    update_interval: never
    accuracy_decimals: 1
    unit_of_measurement: V
    icon: mdi:car-battery

  - name: $PREFIX Battery Max
    id: battery_max_sensor
    platform: template
    lambda: return id(battery_max);
    update_interval: never
    accuracy_decimals: 1
    unit_of_measurement: V
    icon: mdi:car-battery

  - platform: sht3xd
    address: 0x45
    update_interval: $UPDATE_INTERVAL
    temperature:
      id: temp_sensor
      name: $PREFIX Temperature
      retain: false
      filters:
        sliding_window_moving_average:
          window_size: 10
          send_every: 10
    humidity:
      id: humid_sensor
      name: $PREFIX Humidity
      retain: false
      filters:
        sliding_window_moving_average:
          window_size: 10
          send_every: 10

  - id: hour_sensor
    platform: mqtt_subscribe
    topic: time/hour
    on_value_range:
      below: 1 # hour zero => midnight
      then:
        - component.update: battery_min_sensor
        - component.update: battery_max_sensor
        - lambda: id(battery_min) = id(battery).state;
        - lambda: id(battery_max) = id(battery).state;

output:
  - id: d5
    platform: gpio
    pin: D5

  - id: d6
    platform: gpio
    pin: D6

light:
  - platform: binary
    name: Backyard Garden Lights
    output: d5
    restore_mode: ALWAYS_OFF

  - platform: binary
    name: Backyard Fernery Lights
    output: d6
    restore_mode: ALWAYS_OFF

interval:
  - interval: 1min
    then:
      lambda: |-
        if (id(battery).state < id(battery_min)) {
          id(battery_min) = id(battery).state;
        }
        if (id(battery).state > id(battery_max)) {
          id(battery_max) = id(battery).state;
        }
