substitutions:
  <<: !include secrets_ag.yaml
  NAME: backyard_garden_hub
  PREFIX: Backyard Garden Hub
  WIFI_AP_SSID: ESP-BGBH
  REBOOT_TIMEOUT: 120min
  LOG_LEVEL: INFO
  UPDATE_INTERVAL: 10min
  # PINS:
  RAINGAUGE_PIN: D3
  FERNERY_TANK_PIN: D5
  FERNERY_LIGHTS_PIN: D6
  FERNERY_PUMP_PIN: D7
  BACKYARD_LIGHTS_PIN: D8

esphome:
  <<: !include partial/esphome_d1_mini.yaml

globals:
  - id: rainfall_total
    type: float
    restore_value: yes

  - id: pump_enable
    type: bool
    initial_value: "true"
    restore_value: yes

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

  - id: daytime_text_sensor
    platform: mqtt_subscribe
    topic: info/time/daytime

  - id: rain_forecast_text_sensor
    platform: mqtt_subscribe
    topic: info/weather/forecast/today/rain

binary_sensor:
  - id: raingauge_binary
    platform: gpio
    pin: $RAINGAUGE_PIN
    filters:
      - delayed_off: 1ms
    on_release:
      - lambda: id(rainfall_total) += 0.2794;

  - id: water_tank_sensor
    name: $PREFIX Water Tank
    platform: gpio
    pin:
      number: $FERNERY_TANK_PIN
      mode: INPUT_PULLUP
    device_class: moisture
    filters:
      - delayed_on_off: 5s
    on_press:
      then:
        mqtt.publish:
          topic: notify/maintenance/$NAME/water_tank
          payload: ""
          retain: yes
    on_release:
      then:
        mqtt.publish:
          topic: notify/maintenance/$NAME/water_tank
          payload: $PREFIX - Fernery water tank low!
          retain: yes

  - id: daytime_sensor
    platform: template
    lambda: return id(daytime_text_sensor).state == "YES";
    on_press:
      then:
        - light.turn_off: garden_lights
        - light.turn_off: fernery_lights
    on_release:
      then:
        - light.turn_on: garden_lights
        - light.turn_on: fernery_lights

  - platform: template
    id: pump_active_binary_sensor
    name: $PREFIX Pump Active
    lambda: |-
        return (true
          && id(pump_enable)
          && id(water_tank_sensor).state
          && id(daytime_text_sensor).state == "YES"
          // && id(rain_forecast_text_sensor).state != "YES"
        );

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  - name: $PREFIX Rainfall
    platform: template
    lambda: return id(rainfall_total);
    update_interval: 60s
    unit_of_measurement: mm
    accuracy_decimals: 3
    icon: mdi:weather-rainy

  - id: hour_sensor
    platform: mqtt_subscribe
    topic: info/time/hour
    on_value_range:
      above: 1
      below: 2
      then:
        - light.turn_off: garden_lights
        - light.turn_off: fernery_lights

switch:
  - id: pump_enable_switch
    name: $PREFIX Pump Enable
    platform: template
    lambda: return id(pump_enable);
    turn_on_action:
      lambda: id(pump_enable) = true;
    turn_off_action:
      lambda: id(pump_enable) = false;

  # TIP41C
  - id: pump_switch
    name: $PREFIX Pump
    platform: gpio
    pin: $FERNERY_PUMP_PIN
    on_turn_on:
      script.execute: pump_timer

output:
  - id: backyard_lights_relay
    platform: gpio
    pin: $BACKYARD_LIGHTS_PIN

  - id: fernery_lights_relay
    platform: gpio
    pin: $FERNERY_LIGHTS_PIN

light:
  - platform: binary
    id: garden_lights
    name: Backyard Garden Lights
    output: backyard_lights_relay
    restore_mode: ALWAYS_OFF

  - platform: binary
    id: fernery_lights
    name: Backyard Fernery Lights
    output: fernery_lights_relay
    restore_mode: ALWAYS_OFF

time:
  - id: ntp_time
    platform: sntp
    servers:
      - $MQTT_BROKER
    on_time:
      - seconds: 0
        minutes: 0
        hours: 9
        then:
          lambda: id(rainfall_total) = 0;

      - seconds: 0
        minutes: 0
        hours: /1
        then:
          if:
            condition:
              binary_sensor.is_on: pump_active_binary_sensor
            then:
              - switch.turn_on: pump_switch

script:
  - id: pump_timer
    then:
      - delay: 30s
      - switch.turn_off: pump_switch
