substitutions:
  <<: !include secrets_ag.yaml
  NAME: bedroom_lamp
  PREFIX: Bedroom Lamp
  WIFI_AP_SSID: ESP-BL
  REBOOT_TIMEOUT: 120min
  LOG_LEVEL: INFO
  UPDATE_INTERVAL: 5min

esphome:
  <<: !include partial/esphome_sonoff_s26.yaml
  comment: Sonoff S26 No. 3

<<: !include partial/common.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

  - id: daytime_text_sensor
    platform: mqtt_subscribe
    topic: info/time/daytime

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

binary_sensor:
  - id: daytime_sensor
    platform: template
    lambda: return id(daytime_text_sensor).state == "YES";
    on_release:
      then:
        light.turn_on: relay_light

  - id: button_binary_sensor
    platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      delayed_on: 100ms
    on_press:
      then:
        light.toggle: relay_light

output:
  - platform: esp8266_pwm
    id: led_output
    pin:
      number: GPIO13
      inverted: true

  - id: relay_output
    platform: gpio
    pin: GPIO12

light:
  # https://esphome.io/components/light/monochromatic.html
  - id: led_light
    platform: monochromatic
    output: led_output
    restore_mode: ALWAYS_ON

  - id: relay_light
    name: $PREFIX
    platform: binary
    output: relay_output
    restore_mode: ALWAYS_OFF
    on_turn_on:
      light.turn_off: led_light
    on_turn_off:
      light.turn_on:
        id: led_light
        brightness: 50%
