substitutions:
  <<: !include secrets_ag.yaml
  NAME: bedroom_env_sensor
  PREFIX: Bedroom
  WIFI_AP_SSID: ESP-BRES
  REBOOT_TIMEOUT: 0s
  LOG_LEVEL: WARN
  UPDATE_INTERVAL: 5min

esphome:
  <<: !include partial/esphome_d1_mini.yaml

<<: !include partial/environment_sensor.yaml
