## eg: `pipenv run esphome -s ID 1 _____.yaml run`

substitutions:
  NAME: camera_m5_$ID
  PREFIX: Camera M5 $ID
  WIFI_AP_SSID: ESP-M5-$ID
  REBOOT_TIMEOUT: 15min
  LOG_LEVEL: INFO

  # MAX: 800x600 - SVGA (maximum)
  RES: SVGA
  FPS: "10"
  VFLIP: "no"
  HFLIP: "no"

esphome:
  name: $NAME
  platform: ESP32
  board: nodemcu-32s
  build_path: _builds/camera_m5_dev/  

<<: !include partial/wifi.yaml

api:
  reboot_timeout: $REBOOT_TIMEOUT

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

## M5 Cameras without SRAM only support up to SVGA 800×600
## https://docs.m5stack.com/#/en/unit/esp32cam
## https://www.aliexpress.com/item/M5Stack-Official-ESP32-Camera-Development-Board-OV2640-Camera-Type-C-Grove-Port-3D-Wifi-Antenna-Mini/32881414545.html](https://www.aliexpress.com/item/M5Stack-Official-ESP32-Camera-Development-Board-OV2640-Camera-Type-C-Grove-Port-3D-Wifi-Antenna-Mini/32881414545.html
# https://esphome.io/components/esp32_camera.html
esp32_camera:
  name: $PREFIX

  # Pins:
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins:
    - GPIO17
    - GPIO35
    - GPIO34
    - GPIO5
    - GPIO39
    - GPIO18
    - GPIO36
    - GPIO19
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15

  # Image:
  idle_framerate: 0.01 fps
  max_framerate: $FPS fps
  resolution: $RES
  jpeg_quality: 10
  contrast: 0
  brightness: 0
  saturation: 0
  vertical_flip: $VFLIP
  horizontal_mirror: $HFLIP

switch:
  - platform: restart
    name: $PREFIX Restart

  - id: gpio4
    name: $PREFIX GPIO4
    platform: gpio
    pin: GPIO4

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLDOWN
    name: $PREFIX GPIO13

output:
  - id: red_led
    platform: gpio
    pin: GPIO14
    inverted: true

interval:
  - interval: 10s
    then:
      - output.turn_on: red_led
      - delay: 1s
      - output.turn_off: red_led
