substitutions:
  <<: !include secrets_ag.yaml
  NAME: courtyard_garden_lights
  PREFIX: Courtyard Garden Lights
  WIFI_AP_SSID: ESP-C1
  REBOOT_TIMEOUT: 15min
  LOG_LEVEL: INFO

esphome:
  <<: !include partial/esphome_d1_mini.yaml

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

  - id: daytime_text_sensor
    platform: mqtt_subscribe
    topic: info/time/daytime

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  - id: hour_sensor
    platform: mqtt_subscribe
    topic: info/time/hour
    on_value_range:
      above: 1
      below: 2
      then:
        light.turn_off: relay_light

binary_sensor:
  - id: daytime_sensor
    platform: template
    lambda: return id(daytime_text_sensor).state == "YES";
    on_press:
      then:
        light.turn_off: relay_light
    on_release:
      then:
        light.turn_on: relay_light

  - id: button_binary_sensor
    platform: gpio
    pin:
      number: D3
      mode: INPUT
      inverted: true
    filters:
      delayed_on: 100ms
    on_press:
      then:
        light.toggle: relay_light

output:
  - id: relay_output
    platform: gpio
    pin: D1

light:
  - id: relay_light
    name: $PREFIX
    platform: binary
    output: relay_output
    restore_mode: ALWAYS_OFF
