substitutions:
  <<: !include secrets_rc.yaml
  NAME: dam_water_level_alarm
  PREFIX: Dam Water Level
  WIFI_AP_SSID: ESP-DWLA
  REBOOT_TIMEOUT: 0s
  LOG_LEVEL: INFO
  ## PINS ##
  AUDIBLE_OUTPUT_PIN: D1
  LED_OUTPUT_PIN: D3

esphome:
  <<: !include partial/esphome_d1_mini_pro.yaml
  on_boot:
    - wait_until:
        mqtt.connected:
    - mqtt.publish:
        topic: notify/critical/$NAME/alert
        payload: $PREFIX - Alert!
        retain: no

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi_ext.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

binary_sensor:
  - platform: status
    name: $PREFIX Status

switch:
  - platform: shutdown
    name: $PREFIX Shutdown

output:
  - platform: gpio
    id: led_output
    pin: $LED_OUTPUT_PIN

  - platform: gpio
    id: audible_output
    pin:
      number: $AUDIBLE_OUTPUT_PIN
      mode: OUTPUT_OPEN_DRAIN
      inverted: true

script:
  - id: audible_alert
    then:
      - output.turn_on: audible_output
      - delay: 1min
      - output.turn_off: audible_output

interval:
  - interval: 2s
    then:
      - output.turn_on: led_output
      - delay: 1s
      - output.turn_off: led_output

  - interval: 2min
    then:
      if:
        condition:
          lambda: return id(uptime_sensor).state < 600;
        then:
          script.execute: audible_alert

  - interval: 10min
    then:
      script.execute: audible_alert

deep_sleep:
  run_duration: 60min
  sleep_duration: 120min
