substitutions:
  NAME: heater_blanket_switch
  PREFIX: Heater Blanket Switch
  WIFI_AP_SSID: ESP-EBS
  REBOOT_TIMEOUT: 120min
  LOG_LEVEL: INFO
  MQTT_PREFIX: !secret MQTT_PREFIX

esphome:
  <<: !include partial/esphome_sonoff_s26.yaml
  comment: Sonoff S26 No. 2

<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

  - id: daytime_text_sensor
    platform: mqtt_subscribe
    topic: time/daytime

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

binary_sensor:
  - id: daytime_sensor
    platform: template
    lambda: return id(daytime_text_sensor).state.compare("ON") == 0;
    filters:
      delayed_on_off: 2h
    on_press:
      then:
        switch.turn_off: relay_switch
    on_release:
      then:
        switch.turn_on: relay_switch

  - id: button_binary_sensor
    platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    filters:
      delayed_on: 100ms
    on_press:
      then:
        switch.toggle: relay_switch

switch:
  - id: relay_switch
    name: $PREFIX
    platform: gpio
    pin: GPIO12
    restore_mode: ALWAYS_OFF
    on_turn_on:
      light.turn_off: led_light
    on_turn_off:
      light.turn_on:
        id: led_light
        brightness: 50%

output:
  - platform: esp8266_pwm
    id: led_output
    pin:
      number: GPIO13
      inverted: true

light:
  # https://esphome.io/components/light/monochromatic.html
  - id: led_light
    platform: monochromatic
    output: led_output
    restore_mode: ALWAYS_ON
