substitutions:
  <<: !include secrets_ag.yaml
  NAME: kitchen_pantry
  PREFIX: Kitchen Pantry
  WIFI_AP_SSID: ESP-KP
  REBOOT_TIMEOUT: 60min
  LOG_LEVEL: INFO
  UPDATE_INTERVAL: 15min
  ## PINS ##
  RELAY_PIN: D1
  SCANNER_PIN: D2
  MOTION_PIN: D3

esphome:
  <<: !include partial/esphome_d1_mini.yaml
  includes:
    - uart_read_line_sensor.h

logger:
  level: $LOG_LEVEL
  baud_rate: 0 #disable logging over uart

uart:
  id: uart_bus
  rx_pin: $SCANNER_PIN
  baud_rate: 9600

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml

mqtt:
  <<: !include partial/mqtt_defaults.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml
  - <<: !include partial/mqtt_scenes_for_living_room.yaml

  - platform: custom
    lambda: |-
      auto custom_sensor = new UartReadLineSensor(id(uart_bus));
      App.register_component(custom_sensor);
      return {custom_sensor};
    text_sensors:
      name: $PREFIX Barcode

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

binary_sensor:
  - id: pir_binary_sensor
    name: $PREFIX Motion
    device_class: motion
    platform: gpio
    pin:
      number: $MOTION_PIN
      mode: INPUT
    on_press:
      then:
        - light.turn_on: relay_light
        - script.stop: relay_light_timer_script
    on_release:
      then:
        - script.execute: relay_light_timer_script

output:
  - id: relay_output
    platform: gpio
    pin: $RELAY_PIN

light:
  - id: relay_light
    name: $PREFIX Light
    platform: binary
    output: relay_output
    restore_mode: ALWAYS_OFF

script:
  - id: relay_light_timer_script
    mode: restart
    then:
      - delay: 15min
      - light.turn_off: relay_light

  - id: scene_living_room_bright_light
    then:
      light.turn_on: relay_light

  - id: scene_living_room_low_light
    then:
      light.turn_off: relay_light

  - id: scene_living_room_night_light
    then:
      light.turn_off: relay_light

  - id: scene_living_room_all_lights_off
    then:
      light.turn_off: relay_light
