substitutions:
  NAME: laundry
  PREFIX: Laundry
  WIFI_AP_SSID: ESP-LL
  REBOOT_TIMEOUT: 60min
  LOG_LEVEL: INFO
  MQTT_PREFIX: !secret MQTT_PREFIX

esphome:
  <<: !include partial/esphome_d1_mini.yaml

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

binary_sensor:
  - id: pir_binary_sensor
    name: $PREFIX Motion
    device_class: motion
    platform: gpio
    pin:
      number: D3 # D3 is default
      mode: INPUT
    on_press:
      then:
        - light.turn_on: led_light
        - script.stop: light_timer_script
    on_release:
      then:
        - script.execute: light_timer_script

output:
  - id: d5_output
    platform: gpio
    pin: D5

light:
  - id: led_light
    name: $PREFIX Light
    platform: binary
    output: d5_output
    restore_mode: ALWAYS_ON
    on_turn_on:
      then:
        script.execute: light_timer_script

script:
  - id: light_timer_script
    mode: restart
    then:
      - delay: 15min
      - light.turn_off: led_light
