substitutions:
  NAME: living_room_shelf
  PREFIX: Living Room Shelf
  WIFI_AP_SSID: ESP-KP
  REBOOT_TIMEOUT: 15min
  LOG_LEVEL: INFO
  MQTT_PREFIX: !secret MQTT_PREFIX

esphome:
  <<: !include partial/esphome_d1_mini.yaml

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml
  - <<: !include partial/mqtt_scenes_for_living_room.yaml

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

output:
  - id: relay_output
    platform: gpio
    pin: D1

light:
  - id: relay_light
    name: $PREFIX Light
    platform: binary
    output: relay_output
    restore_mode: ALWAYS_OFF

script:
  - id: scene_living_room_bright_light
    then:
      light.turn_on: relay_light

  - id: scene_living_room_low_light
    then:
      light.turn_off: relay_light

  - id: scene_living_room_night_light
    then:
      light.turn_off: relay_light

  - id: scene_living_room_all_lights_off
    then:
      light.turn_off: relay_light
