substitutions:
  <<: !include secrets_ag.yaml
  NAME: living_room_env_sensor
  PREFIX: Living Room
  WIFI_AP_SSID: ESP-LRES
  REBOOT_TIMEOUT: 0s
  LOG_LEVEL: WARN
  UPDATE_INTERVAL: 5min

esphome:
  <<: !include partial/esphome_d1_mini.yaml

<<: !include partial/environment_sensor.yaml
