substitutions:
  <<: !include secrets_ag.yaml
  NAME: living_room_ir
  PREFIX: Living Room
  WIFI_AP_SSID: ESP-LRS
  REBOOT_TIMEOUT: 15min
  UPDATE_INTERVAL: 15min
  LOG_LEVEL: WARN
  ## PINS ##
  I2C_1_PIN: D1
  I2C_2_PIN: D2
  PIR_MOTION_PIN: D3
  IR_RECEIVER_PIN: D4
  IR_TRANSMITTER_PIN: D5

esphome:
  <<: !include partial/esphome_d1_mini.yaml
  on_boot:
    - delay: 1s
    - remote_transmitter.transmit_raw:
        code: [-100, 100, -100]

i2c:

<<: !include partial/common.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  - platform: sht3xd
    address: 0x45
    update_interval: 10s
    temperature:
      id: temperature_sensor
      name: $PREFIX Inverter Temperature
      accuracy_decimals: 0
      filters:
        sliding_window_moving_average:
          window_size: 6
          send_every: 6
    humidity:
      id: humid_sensor
      accuracy_decimals: 0
      filters:
        sliding_window_moving_average:
          window_size: 6
          send_every: 6

  - platform: mqtt_subscribe
    name: $PREFIX AC Outside Temp
    id: outside_temp
    topic: info/weather/current/temperature

binary_sensor:
  - name: $PREFIX AC Outside Cooler
    platform: template
    lambda: |-
      return
        id(outside_temp).has_state() 
        && id(daikin_inverter).mode == esphome::climate::ClimateMode::CLIMATE_MODE_COOL
        && id(outside_temp).state < id(daikin_inverter).target_temperature;
    filters:
      delayed_on_off: 15min
    on_press:
      then:
        mqtt.publish:
          topic: notify/warning/$NAME/ac/outside_cooler
          payload: "Outside is cooler but the air-conditioner is on!"
          retain: no

  - name: $PREFIX AC Outside Warmer
    platform: template
    lambda: |-
      return
        id(outside_temp).has_state() 
        && id(daikin_inverter).mode == esphome::climate::ClimateMode::CLIMATE_MODE_HEAT
        && id(outside_temp).state > id(daikin_inverter).target_temperature;
    filters:
      delayed_on_off: 15min
    on_press:
      then:
        mqtt.publish:
          topic: notify/warning/$NAME/ac/outwide_warmer
          payload: "Outside is warmer but the heater is on!"
          retain: no

  - name: $PREFIX Motion
    device_class: motion
    platform: gpio
    pin:
      number: $PIR_MOTION_PIN
      mode: INPUT
    filters:
      delayed_off: 15min

  - id: ir_light_up
    platform: remote_receiver
    nec:
      address: 0x00F7
      command: 0x00FF
    on_press:
      then:
        mqtt.publish:
          topic: scene/living_room
          payload: BRIGHT_LIGHT
          retain: no
          qos: 1

  - id: ir_light_down
    platform: remote_receiver
    nec:
      address: 0x00F7
      command: 0x807F
    on_press:
      then:
        mqtt.publish:
          topic: scene/living_room
          payload: LOW_LIGHT
          retain: no
          qos: 1

  - id: ir_light_on
    platform: remote_receiver
    nec:
      address: 0x00F7
      command: 0xC03F # ON
    on_press:
      then:
        mqtt.publish:
          topic: scene/living_room
          payload: BRIGHT_LIGHT
          retain: no
          qos: 1

  - id: ir_light_off
    platform: remote_receiver
    nec:
      address: 0x00F7
      command: 0x40BF # OFF
    on_press:
      then:
        mqtt.publish:
          topic: scene/living_room
          payload: NIGHT_LIGHT
          retain: no
          qos: 1

  - id: ir_grow_light_off
    platform: remote_receiver
    nec:
      address: 0x00F7
      command: 0xA05F # G
    on_press:
      then:
        mqtt.publish_json:
          topic: device/kitchen_grow_light/light/kitchen_grow_light/command
          payload: root["state"] = "OFF";
          retain: no
          qos: 1

remote_transmitter:
  pin:
    number: $IR_TRANSMITTER_PIN
    inverted: no
  carrier_duty_percent: 50%

## https://www.esphome.io/components/remote_receiver.html
remote_receiver:
  id: ir_receiver
  # dump: all
  pin:
    number: $IR_RECEIVER_PIN
    inverted: yes

climate:
  ## https://www.esphome.io/components/climate/ir_climate.html?highlight=daikin
  ## https://github.com/esphome/esphome/blob/dev/esphome/components/daikin/daikin.h
  - &daikin
    platform: daikin
    name: $PREFIX Inverter
    id: daikin_inverter
    receiver_id: ir_receiver
    sensor: temperature_sensor
    supports_cool: true
    supports_heat: true

switch:
  # https://www.esphome.io/components/climate/index.html#climate-control-action
  - platform: template
    name: $PREFIX Air Conditioner
    lambda: return id(daikin_inverter).mode == esphome::climate::ClimateMode::CLIMATE_MODE_COOL;
    restore_state: no
    turn_on_action:
      climate.control:
        id: daikin_inverter
        mode: COOL
        target_temperature: 25
        fan_mode: LOW
        swing_mode: "OFF"
    turn_off_action:
      climate.control:
        id: daikin_inverter
        mode: "OFF"

  - platform: template
    name: $PREFIX Heater
    lambda: return id(daikin_inverter).mode == esphome::climate::ClimateMode::CLIMATE_MODE_HEAT;
    restore_state: no
    turn_on_action:
      climate.control:
        id: daikin_inverter
        mode: HEAT
        target_temperature: 21
        fan_mode: LOW
        swing_mode: "OFF"
    turn_off_action:
      climate.control:
        id: daikin_inverter
        mode: "OFF"

  # - platform: template
  #   name: $PREFIX Silent Fan
  #   turn_on_action:
  #     climate.control:
  #       id: daikin_inverter
  #       custom_fan_mode: DAIKIN_FAN_SILENT

  ############### Air Filter ###############

  - platform: template
    name: $PREFIX Air Filter Power
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x0057
        command: 0x837C

  - platform: template
    name: $PREFIX Air Filter Speed
    turn_on_action:
      remote_transmitter.transmit_nec:
        address: 0x0057
        command: 0x817E

  ############### Sony TV ###############

  - platform: template
    name: $PREFIX Sony TV Power
    turn_on_action:
      remote_transmitter.transmit_sony:
        data: 0x00000A90
        nbits: 12
        repeat: 3

  - platform: template
    name: $PREFIX Sony TV Mute
    turn_on_action:
      remote_transmitter.transmit_sony:
        data: 0x00000290
        nbits: 12
        repeat: 3

  - platform: template
    name: $PREFIX Sony TV Volume Up
    turn_on_action:
      remote_transmitter.transmit_sony:
        data: 0x00000490
        nbits: 12
        repeat: 3

  - platform: template
    name: $PREFIX Sony TV Volume Down
    turn_on_action:
      remote_transmitter.transmit_sony:
        data: 0x00000C90
        nbits: 12
        repeat: 3
