substitutions:
  <<: !include secrets_ag.yaml
  NAME: optic_fibre_lamp
  PREFIX: Optic Fibre
  WIFI_AP_SSID: ESP-OFL
  REBOOT_TIMEOUT: 60min
  LOG_LEVEL: INFO

esphome:
  <<: !include partial/esphome_d1_mini.yaml
  on_boot:
    - delay: 1s
    - light.turn_on:
        id: leds
        effect: Random Twinkle

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

  - id: daytime_text_sensor
    platform: mqtt_subscribe
    topic: info/time/daytime

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  - id: hour_sensor
    platform: mqtt_subscribe
    topic: info/time/hour
    on_value_range:
      above: 0
      below: 1
      then:
        light.turn_off: leds

binary_sensor:
  - id: daytime_sensor
    platform: template
    lambda: return id(daytime_text_sensor).state == "YES";
    on_press:
      then:
        light.turn_off: leds
    on_release:
      then: &turn_on_random_twinkle
        light.turn_on:
          id: leds
          effect: Random Twinkle

  - id: button
    name: $PREFIX Button
    platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    filters:
      delayed_on: 100ms
    on_press: &toggle
      then:
        if:
          condition:
            light.is_off: leds
          then:
            <<: *turn_on_random_twinkle
          else:
            light.turn_off: leds
    on_release:
      <<: *toggle

light:
  - platform: neopixelbus
    variant: WS2812
    method: ESP8266_UART1
    type: GRB
    pin: D4
    num_leds: 7
    id: leds
    name: $PREFIX Light
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_fireworks:
          name: Nightclub
          spark_probability: 95%
          use_random_color: no
          fade_out_rate: 200
      - addressable_fireworks:
          name: Chaos
          spark_probability: 95%
          use_random_color: no
          fade_out_rate: 50
      - addressable_flicker:
          name: Flicker


