substitutions:
  <<: !include secrets_ag.yaml
  NAME: patio_floodlight
  PREFIX: Patio Floodlight
  SHORT_PREFIX: Patio
  WIFI_AP_SSID: ESP-PFL
  REBOOT_TIMEOUT: 15min
  LOG_LEVEL: INFO
  UPDATE_INTERVAL: 15min
  ## PINS ##
  LIGHT_PIN: D1
  PIR_PIN: D2
  PIR_ENABLED_PIN: D7

esphome:
  name: $NAME
  platform: ESP8266
  board: d1_mini
  build_path: _builds/$NAME/

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

  - id: security_enabled
    platform: mqtt_subscribe
    topic: security/enabled

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

## https://esphome.io/components/binary_sensor/index.html
binary_sensor:
  - id: pir_gpio
    platform: gpio
    pin:
      number: $PIR_PIN
      mode: INPUT_PULLUP
    device_class: motion
    on_press:
      if:
        condition:
          switch.is_on: sensor_enabled
        then:
          script.execute: sensor_timer

  - name: $SHORT_PREFIX Motion
    platform: template
    lambda: return id(pir_gpio).state;
    filters:
      delayed_off: 10min
    on_press:
      mqtt.publish:
        topic: security/state/motion/outside/$SHORT_PREFIX
        payload: detected
        retain: no

  - id: pir_security_alert
    platform: template
    lambda: return id(pir_gpio).state;
    filters:
      delayed_off: 30min
    on_press:
      if:
        condition:
          lambda: id(security_enabled).state == "YES";
        then:
          mqtt.publish:
            topic: notify/critical/$SHORT_PREFIX/motion
            payload: $SHORT_PREFIX motion detected!
            retain: no

output:
  - id: light_output
    platform: gpio
    pin: $LIGHT_PIN

light:
  - id: flood
    platform: binary
    name: $SHORT_PREFIX Light
    output: light_output

switch:
  - id: sensor_enabled
    name: $SHORT_PREFIX Sensor
    platform: gpio
    pin: $PIR_ENABLED_PIN
    on_turn_off:
      light.turn_off: flood

script:
  - id: sensor_timer
    mode: restart
    then:
      - light.turn_on: flood
      - delay: 5min
      - light.turn_off: flood
