substitutions:
  <<: !include secrets_rc.yaml
  NAME: rc_dam_water_level_alarm
  PREFIX: Dam Water Level
  WIFI_AP_SSID: ESP-RC-DWLA
  REBOOT_TIMEOUT: 0s
  LOG_LEVEL: INFO

esphome:
  <<: !include partial/esphome_d1_mini_pro.yaml

<<: !include partial/wemos_d1_mini_status_led.yaml

logger:
  level: $LOG_LEVEL

wifi:
  id: wifi_id
  networks:
    - ssid: $WIFI_SSID
      password: $WIFI_PASSWORD
    - ssid: $WIFI_SSID_EXT
      password: $WIFI_PASSWORD
  reboot_timeout: $REBOOT_TIMEOUT
  ap:
    ssid: $WIFI_AP_SSID
    password: $WIFI_AP_PASSWORD

captive_portal:

ota:
  password: $OTA_PASSWORD

mqtt:
  id: mqtt_client
  broker: $MQTT_BROKER
  username: $MQTT_USERNAME
  password: $MQTT_PASSWORD
  discovery_prefix: $MQTT_PREFIX/homeassistant
  topic_prefix: $MQTT_PREFIX/$NAME
  reboot_timeout: $REBOOT_TIMEOUT

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

binary_sensor:
  - platform: status
    name: $PREFIX Status

switch:
  - platform: shutdown
    name: $PREFIX Shutdown

output:
  - platform: gpio
    id: led_output
    pin: D3

  - platform: gpio
    id: audible_output
    pin:
      number: D1
      mode: OUTPUT_OPEN_DRAIN
      inverted: true

script:
  - id: audible_alert
    then:
      - output.turn_on: audible_output
      - delay: 1min
      - output.turn_off: audible_output

interval:
  - interval: 2s
    then:
      - output.turn_on: led_output
      - delay: 1s
      - output.turn_off: led_output

  - interval: 2min
    then:
      if:
        condition:
          lambda: return id(uptime_sensor).state < 600;
        then:
          script.execute: audible_alert

  - interval: 10min
    then:
      script.execute: audible_alert

deep_sleep:
  run_duration: 60min
  sleep_duration: 120min
