substitutions:
  # <<: !include secrets_rc.yaml
  <<: !include secrets_ag.yaml
  NAME: shed_water_tank
  PREFIX: Shed Water Tank
  WIFI_AP_SSID: ESP-SWT
  REBOOT_TIMEOUT: 0s
  LOG_LEVEL: DEBUG
  ## PINS ##
  ULTRASONIC_TRIGGER_PIN: D6
  ULTRASONIC_ECHO_PIN: D7

esphome:
  <<: !include partial/esphome_d1_mini_pro.yaml

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  # https://esphome.io/components/sensor/ultrasonic.html
  - id: tank_depth
    name: $PREFIX Depth
    platform: ultrasonic
    trigger_pin: $ULTRASONIC_TRIGGER_PIN
    echo_pin: $ULTRASONIC_ECHO_PIN
    pulse_time: 10us
    timeout: 5m
    filters:
      lambda: return 3 - x;
    update_interval: 10min
    availability:
      topic: null/always_online
      payload_available: online
      payload_not_available: online
