substitutions:
  <<: !include secrets_rc.yaml
  NAME: shed_water_tank
  PREFIX: Shed Tank
  WIFI_AP_SSID: ESP-ST
  REBOOT_TIMEOUT: 0s
  LOG_LEVEL: INFO
  ## PINS ##
  LIGHT_SENSOR_PIN: A0
  I2C_1_PIN: D1
  I2C_2_PIN: D2
  BUTTON_PIN: D3
  STATUS_LED_PIN: D4
  VALVE_PIN_1: D5
  FLOW_SENSOR_PIN: D6
  PUMP_PIN: D7
  VALVE_PIN_2: D8

esphome:
  <<: !include partial/esphome_d1_mini.yaml
  on_boot:
    - delay: 15min
    - globals.set:
        id: initialized
        value: 'true'

globals:
  - id: initialized
    type: bool
    restore_value: no
    initial_value: 'false'

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi_ext.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  - id: flow
    name: $PREFIX Flow
    platform: pulse_counter
    pin: $FLOW_SENSOR_PIN
    update_interval: 1s
    accuracy_decimals: 0
    filters:
      sliding_window_moving_average:
        window_size: 30
        send_every: 30

  - id: light_sensor
    name: $PREFIX Light
    platform: adc
    pin: $LIGHT_SENSOR_PIN
    update_interval: 1min
    filters:
      - multiply: 3.3 
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10

binary_sensor:
  - id: button
    name: $PREFIX Button
    platform: gpio
    pin:
      number: $BUTTON_PIN
      mode: INPUT
      inverted: true
    filters:
      delayed_on: 100ms
    on_press:
      then:
        switch.toggle: pump

  - id: daylight
    name: $PREFIX Daylight
    device_class: light
    platform: template
    lambda: return id(light_sensor).state > 1.0;
    filters:
      delayed_on_off: 10min
    on_press:
      then:
        if:
          condition:
            lambda: return id(initialized);
          then:
            switch.turn_on: pump

  - name: $PREFIX Pump Enabled
    platform: template
    lambda: return id(pump).state && id(flow).raw_state < 100;
    filters:
      delayed_on: 3s
    on_press:
      - switch.turn_off: pump
      - mqtt.publish:
          topic: notify/warning/$NAME/no_water_flow
          payload: $PREFIX - No water flow!
          retain: yes
    on_release:
      - mqtt.publish:
          topic: notify/warning/$NAME/no_water_flow
          payload: ""
          retain: yes

switch:
  # TIP41C
  - id: valve_1
    name: $PREFIX Valve 1
    platform: gpio
    pin: $VALVE_PIN_1

  # TIP122
  - id: valve_2
    name: $PREFIX Valve 2
    platform: gpio
    pin: $VALVE_PIN_2

  - id: pump
    name: $PREFIX Pump
    platform: gpio
    pin: $PUMP_PIN
    on_turn_on:
      - script.execute: pump_timer
    on_turn_off:
      - switch.turn_off: valve_1
      - switch.turn_off: valve_2
      - script.stop: pump_timer

script:
  - id: pump_timer
    then:
      - switch.turn_on: valve_1
      - delay: 1s
      - switch.turn_off: valve_2
      - delay: 5min
      - switch.turn_on: valve_2
      - delay: 1s
      - switch.turn_off: valve_1
      - delay: 5min
      - switch.turn_off: pump
