## Retrofit for old toy slot car track

substitutions:
  <<: !include secrets_ag.yaml
  NAME: slot_car_track
  PREFIX: Slot Car Track
  WIFI_AP_SSID: ESP-SCT
  REBOOT_TIMEOUT: 0s
  LOG_LEVEL: INFO
  ## VARS ##
  ACC_TIME: 1000ms
  SLOW_TIME: 1500ms
  BRAKE_TIME: 500ms
  MIN_SPEED: 85%
  MAX_SPEED: 95%
  BRAKE_SPEED: 75%

esphome:
  <<: !include partial/esphome_lolin_d32_pro.yaml

status_led:
  pin:
    number: GPIO5
    inverted: true

<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

binary_sensor:
  - id: acc_1
    name: $PREFIX Acc 1
    platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.turn_on:
          id: track_1
          brightness: $MAX_SPEED
          transition_length: $ACC_TIME
    on_release:
      - light.turn_on:
          id: track_1
          brightness: $MIN_SPEED
          transition_length: $SLOW_TIME

  - id: brake_1
    name: $PREFIX Brake 1
    platform: gpio
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.turn_on:
          id: track_1
          brightness: $BRAKE_SPEED
          transition_length: $BRAKE_TIME
    on_release:
      - light.turn_on:
          id: track_1
          brightness: $MIN_SPEED
          transition_length: 0s

  - id: acc_2
    name: $PREFIX Acc 2
    platform: gpio
    pin:
      number: GPIO22
      mode: INPUT_PULLUP
      inverted: true

  - id: brake_2
    name: $PREFIX Brake 2
    platform: gpio
    pin:
      number: GPIO23
      mode: INPUT_PULLUP
      inverted: true

output:
  - platform: ledc
    pin: GPIO25
    id: gpio_25
    frequency: 1220Hz

  - platform: ledc
    pin: GPIO26
    id: gpio_26
    frequency: 1220Hz

light:
  - platform: monochromatic
    output: gpio_25
    id: track_1
    name: $PREFIX Track 1
    default_transition_length: 0s

  - platform: monochromatic
    output: gpio_26
    id: track_2
    name: $PREFIX Track 2
    default_transition_length: 0s
