substitutions:
  NAME: solar_hws_ctl
  PREFIX: HWS Ctl
  WIFI_AP_SSID: ESP-$NAME
  REBOOT_TIMEOUT: 120min
  LOG_LEVEL: INFO
  MQTT_PREFIX: !secret MQTT_PREFIX
  TANK_MAX_TEMP: "80"
  SOLAR_MAX_TEMP: "100"

esphome:
  name: $NAME
  platform: ESP8266
  board: d1_mini
  build_path: _builds/$NAME/
  on_boot:
    - delay: 10s
    - climate.control:
        id: tank_target
        mode: HEAT

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

i2c:

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

# https://esphome.io/components/sensor/index.html
sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  - id: adc_sensor
    platform: adc
    pin: A0
    update_interval: never
    filters:
      - multiply: 1024

  - id: solar_temp_sensor
    platform: template
    lambda: return (id(adc_sensor).state - 288.6) / 6.38;
    # lambda: return (id(adc_sensor).state - 36.1997) / 6.26956;
    update_interval: never

  - id: tank_temp_sensor
    platform: template
    lambda: return (id(adc_sensor).state - 285.54) / 5.269;
    # lambda: return (id(adc_sensor).state - 36.1997) / 6.26956;
    update_interval: never

  - name: $PREFIX Solar
    platform: template
    unit_of_measurement: °C
    accuracy_decimals: 0
    lambda: return id(solar_temp_sensor).state;
    retain: false
    update_interval: 1min
    filters:
      - median:
          window_size: 10
          send_every: 10

  - name: $PREFIX Tank
    platform: template
    unit_of_measurement: °C
    accuracy_decimals: 0
    lambda: return id(tank_temp_sensor).state;
    retain: false
    update_interval: 1min
    filters:
      - median:
          window_size: 10
          send_every: 10

switch:
  - id: pump_switch
    name: $PREFIX Pump
    platform: gpio
    pin: D8
    retain: false
    restore_mode: ALWAYS_OFF

  - id: solar_ntc_switch
    platform: gpio
    restore_mode: ALWAYS_OFF
    pin: D5

  - id: tank_ntc_switch
    platform: gpio
    restore_mode: ALWAYS_OFF
    pin: D6

climate:
  - id: tank_target
    name: $PREFIX Tank Target
    platform: thermostat
    sensor: tank_temp_sensor
    default_target_temperature_low: 65 °C
    heat_action:
      delay: 1s
    idle_action:
      delay: 1s
    visual:
      min_temperature: 50 °C
      max_temperature: $TANK_MAX_TEMP °C
      temperature_step: 1 °C

interval:
  - interval: 10s
    then:
      - switch.turn_on: solar_ntc_switch
      - component.update: adc_sensor
      - switch.turn_off: solar_ntc_switch
      - component.update: solar_temp_sensor
      - switch.turn_on: tank_ntc_switch
      - component.update: adc_sensor
      - switch.turn_off: tank_ntc_switch
      - component.update: tank_temp_sensor
      - if:
          condition:
            lambda: |-
                return (
                  id(tank_temp_sensor).state <= id(tank_target).target_temperature &&
                  id(tank_temp_sensor).state <= $TANK_MAX_TEMP &&
                  id(solar_temp_sensor).state <= $SOLAR_MAX_TEMP
                );
          then:
            if:
              condition:
                lambda: return id(solar_temp_sensor).state - id(tank_temp_sensor).state >= 12;
              then:
                switch.turn_on: pump_switch
              else:
                if:
                  condition:
                    lambda: return id(solar_temp_sensor).state - id(tank_temp_sensor).state < 6;
                  then:
                    switch.turn_off: pump_switch
          else:
            switch.turn_off: pump_switch

font:
  # https://www.dafont.com/andrew-tyler.d2526
  - id: mono
    file: 'pixelmix.ttf'
    size: 8

display:
  - platform: ssd1306_i2c
    model: SSD1306 64x48
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(mono), TextAlign::TOP_LEFT, "WIFI: %.0f %s", id(wifi_rssi).state, id(mqtt_client).is_connected() ? "OK" : "--");
      it.printf(0, 10, id(mono), TextAlign::TOP_LEFT, "SOLAR: %.0f", id(solar_temp_sensor).state);
      it.printf(0, 20, id(mono), TextAlign::TOP_LEFT, "TANK: %.0f", id(tank_temp_sensor).state);
      it.printf(0, 30, id(mono), TextAlign::TOP_LEFT, "TARGET: %.0f", id(tank_target).target_temperature_low);
      it.printf(0, 40, id(mono), TextAlign::TOP_LEFT, "PUMP: %s", id(pump_switch).state ? "ON" : "OFF");

