substitutions:
  NAME: solar_hws_ctl
  PREFIX: HWS Ctl
  WIFI_AP_SSID: ESP-$NAME
  REBOOT_TIMEOUT: 120min
  LOG_LEVEL: INFO
  MQTT_PREFIX: !secret MQTT_PREFIX
  TANK_MAX_TEMP: "80"
  SOLAR_MAX_TEMP: "100"

esphome:
  name: $NAME
  platform: ESP8266
  board: d1_mini
  build_path: _builds/$NAME/
  on_boot:
    - delay: 10s
    - climate.control:
        id: tank_target
        mode: HEAT

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

i2c:

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

# https://esphome.io/components/sensor/index.html
sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  - id: adc_sensor
    platform: adc
    pin: A0
    update_interval: never
    filters:
      - multiply: 1024

  - id: solar_temp_sensor
    name: $PREFIX Solar
    platform: template
    unit_of_measurement: °C
    accuracy_decimals: 0
    ## HWS:
    lambda: return (id(adc_sensor).state - 288.6) / 6.38;
    ## BBQ:
    # lambda: return (id(adc_sensor).state - 36.1997) / 6.26956;
    update_interval: never
    retain: false

  - id: tank_temp_sensor
    name: $PREFIX Tank
    platform: template
    unit_of_measurement: °C
    accuracy_decimals: 0
    ## HWS:
    lambda: return (id(adc_sensor).state - 285.54) / 5.269;
    ## BBQ:
    # lambda: return (id(adc_sensor).state - 36.1997) / 6.26956;
    update_interval: never
    retain: false

  - id: tank_solar_diff_temp_sensor
    name: $PREFIX Tank-Solar Difference
    platform: template
    unit_of_measurement: °C
    accuracy_decimals: 0
    lambda: return id(solar_temp_sensor).state - id(tank_temp_sensor).state;
    update_interval: never
    retain: false

binary_sensor:
  # Absolute maximum tank temperature, regardless of thermostat:
  - id: tank_below_max_sensor
    name: $PREFIX Tank Below Max
    platform: template
    lambda: return id(tank_temp_sensor).state < $TANK_MAX_TEMP;
    retain: false
    on_release:
      then:
        - switch.turn_off: pump_switch

  # Below vaporisation point:
  - id: solar_below_max_sensor
    name: $PREFIX Solar Below Max
    platform: template
    lambda: return id(solar_temp_sensor).state < $SOLAR_MAX_TEMP;
    retain: false
    on_release:
      then:
        - switch.turn_off: pump_switch

switch:
  - id: pump_switch
    name: $PREFIX Pump
    platform: gpio
    pin: D8
    retain: false
    restore_mode: ALWAYS_OFF
    # Safety override:
    on_turn_on:
        then:
          - if:
              condition:
                or:
                  - binary_sensor.is_off: tank_below_max_sensor
                  - binary_sensor.is_off: solar_below_max_sensor
              then:
                - switch.turn_off: pump_switch

  - id: heating_mode_switch
    name: $PREFIX Heating Mode
    platform: gpio
    pin: D7
    retain: false
    restore_mode: ALWAYS_OFF
    on_turn_off:
      then:
        - switch.turn_off: pump_switch

  - id: solar_ntc_switch
    platform: gpio
    restore_mode: ALWAYS_OFF
    pin: D5

  - id: tank_ntc_switch
    platform: gpio
    restore_mode: ALWAYS_OFF
    pin: D6

climate:
  - id: tank_target
    name: $PREFIX Tank Target
    platform: thermostat
    sensor: tank_temp_sensor
    default_target_temperature_low: 65 °C
    heat_action:
      - switch.turn_on: heating_mode_switch
    idle_action:
      - switch.turn_off: heating_mode_switch
    visual:
      min_temperature: 0 °C
      max_temperature: $TANK_MAX_TEMP °C
      temperature_step: 1 °C

interval:
  - interval: 10s
    then:
      - switch.turn_on: solar_ntc_switch
      - component.update: adc_sensor
      - switch.turn_off: solar_ntc_switch
      - component.update: solar_temp_sensor
      - switch.turn_on: tank_ntc_switch
      - component.update: adc_sensor
      - switch.turn_off: tank_ntc_switch
      - component.update: tank_temp_sensor
      - component.update: tank_solar_diff_temp_sensor
      - if:
          condition:
            and:
              - switch.is_on: heating_mode_switch
              - binary_sensor.is_on: tank_below_max_sensor
              - binary_sensor.is_on: solar_below_max_sensor
          then:
            if:
              condition:
                sensor.in_range:
                  id: tank_solar_diff_temp_sensor
                  above: 12.0
              then:
                switch.turn_on: pump_switch
              else:
                if:
                  condition:
                    sensor.in_range:
                      id: tank_solar_diff_temp_sensor
                      below: 6.0
                  then:
                    switch.turn_off: pump_switch
          else:
            switch.turn_off: pump_switch

font:
  # https://www.dafont.com/andrew-tyler.d2526
  - id: mono
    file: 'pixelmix.ttf'
    size: 8

display:
  - platform: ssd1306_i2c
    model: SSD1306 64x48
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(mono), TextAlign::TOP_LEFT, "WIFI: %.0f %s", id(wifi_rssi).state, id(mqtt_client).is_connected() ? "OK" : "--");
      it.printf(0, 8, id(mono), TextAlign::TOP_LEFT, "SOLAR: %.0f", id(solar_temp_sensor).state);
      it.printf(0, 16, id(mono), TextAlign::TOP_LEFT, "TANK: %.0f", id(tank_temp_sensor).state);
      it.printf(0, 24, id(mono), TextAlign::TOP_LEFT, "TARGET: %.0f", id(tank_target).target_temperature_low);
      it.printf(0, 32, id(mono), TextAlign::TOP_LEFT, "HEATING: %s", id(heating_mode_switch).state ? "ON" : "OFF");
      it.printf(0, 40, id(mono), TextAlign::TOP_LEFT, "PUMP: %s", id(pump_switch).state ? "ON" : "OFF");

