substitutions:
  <<: !include secrets_ag.yaml
  NAME: studio_psu
  PREFIX: Studio PSU
  WIFI_AP_SSID: ESP-SPSU
  REBOOT_TIMEOUT: 180min
  LOG_LEVEL: INFO
  UPDATE_INTERVAL: 15min
  ## PINS:
  FAN_HIGH_PIN: D5
  PSU_POWER_PIN: D6
  FAN_LOW_PIN: D7

esphome:
  <<: !include partial/esphome_d1_mini.yaml

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

i2c:

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

  - platform: sht3xd
    address: 0x45
    update_interval: 10s
    temperature:
      id: temp_sensor
      name: $PREFIX Temperature
      filters:
        sliding_window_moving_average:
          window_size: 6
          send_every: 6
    humidity:
      id: humid_sensor

binary_sensor:
  - platform: template
    name: $PREFIX Temperature Critical
    lambda: return id(temp_sensor).raw_state >= 50;
    filters:
      - delayed_off: 5min
    on_press:
      then:
        - switch.turn_off: power_switch
        - mqtt.publish:
            topic: notify/critical/$NAME/temperature
            payload: $PREFIX - Temperature Critical
            retain: no
    on_release:
      - switch.turn_on: power_switch

  - platform: template
    name: $PREFIX Temperature High
    lambda: return id(temp_sensor).raw_state >= 40;
    filters:
      - delayed_off: 5min
    on_press:
      then:
        - switch.turn_on: fan_high
        - mqtt.publish:
            topic: notify/warning/$NAME/temperature
            payload: $PREFIX - Temperature High
            retain: yes
    on_release:
      then:
        - switch.turn_off: fan_high
        - mqtt.publish:
            topic: notify/warning/$NAME/temperature
            payload: ""
            retain: yes

switch:
  - id: power_switch
    name: $PREFIX Power
    platform: gpio
    pin: $PSU_POWER_PIN
    restore_mode: ALWAYS_ON
    inverted: yes
    on_turn_on:
      then:
        - switch.turn_on: fan_high
        - switch.turn_on: fan_low
        - delay: 3s
        - switch.turn_off: fan_high

  # 3.9k
  - id: fan_high
    name: $PREFIX Fan High
    platform: gpio
    pin: $FAN_HIGH_PIN
    restore_mode: ALWAYS_ON

  # 5.6k
  - id: fan_low
    name: $PREFIX Fan Low
    platform: gpio
    pin: $FAN_LOW_PIN
    restore_mode: ALWAYS_ON
