substitutions:
  NAME: studio_desk
  PREFIX: Studio Desk
  WIFI_AP_SSID: ESP-SD
  REBOOT_TIMEOUT: 15min
  LOG_LEVEL: INFO
  MQTT_PREFIX: !secret MQTT_PREFIX

esphome:
  <<: !include partial/esphome_d1_mini.yaml

<<: !include partial/wemos_d1_mini_status_led.yaml
<<: !include partial/wifi.yaml
<<: !include partial/mqtt.yaml

text_sensor:
  - <<: !include partial/wifi_ip_addr_text_sensor.yaml

  - id: daytime_text_sensor
    platform: mqtt_subscribe
    topic: time/daytime

sensor:
  - <<: !include partial/wifi_rssi_sensor.yaml
  - <<: !include partial/uptime_sensor.yaml

binary_sensor:
  - id: daytime_sensor
    platform: template
    lambda: return id(daytime_text_sensor).state.compare("ON") == 0;
    on_press:
      then:
        light.turn_off: underside_light
    on_release:
      then:
        light.turn_on:
          id: underside_light
          brightness: 50%

  - id: button_binary_sensor
    platform: gpio
    pin:
      number: D3
      mode: INPUT
      inverted: true
    filters:
      delayed_on: 100ms
    on_press:
      then:
        light.toggle: underside_light

output:
  - platform: esp8266_pwm
    id: d1_output
    pin: D1

light:
  # https://esphome.io/components/light/monochromatic.html
  - id: underside_light
    name: $PREFIX Underside Light
    platform: monochromatic
    output: d1_output
    restore_mode: ALWAYS_OFF
