esphome:
  name: $NAME
  platform: ESP32
  board: nodemcu-32s
  build_path: _builds/$NAME/

<<: !include ../wifi.yaml

api:
  reboot_timeout: $REBOOT_TIMEOUT

text_sensor:
  - <<: !include ../wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include ../wifi_rssi_sensor.yaml
  - <<: !include ../uptime_sensor.yaml

## M5 Cameras with PSRAM support up to SXGA 1280×1024
## M5CameraF (Fish Eye)
## https://docs.m5stack.com/#/en/unit/m5camera_f
## M5CameraX (Normal)
## https://github.com/m5stack/m5stack-cam-psram

# https://esphome.io/components/esp32_camera.html
esp32_camera:
  name: $PREFIX

  # Pins:
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO22
    scl: GPIO23
  data_pins:
    - GPIO32
    - GPIO35
    - GPIO34
    - GPIO5
    - GPIO39
    - GPIO18
    - GPIO36
    - GPIO19
  vsync_pin: GPIO25
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15

  # Image:
  idle_framerate: 0.01 fps
  max_framerate: $CAMERA_MAX_FRAMERATE
  resolution: $CAMERA_RESOLUTION
  jpeg_quality: 10
  contrast: 0
  brightness: 0
  saturation: 0
  vertical_flip: $CAMERA_VERTICAL_FLIP
  horizontal_mirror: $CAMERA_HORIZONTAL_MIRROR

switch:
  - platform: restart
    name: $PREFIX Restart

  - id: red_led
    name: $PREFIX Red LED
    platform: gpio
    pin: GPIO14
    inverted: true
    restore_mode: ALWAYS_ON

  - id: gpio4
    name: $PREFIX GPIO4
    platform: gpio
    pin: GPIO4

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLDOWN
    name: $PREFIX GPIO13

interval:
  - interval: 60s
    then:
      - switch.turn_on: red_led
      - delay: 1s
      - switch.turn_off: red_led
