<<: !include ./wifi.yaml

# https://esphome.io/components/logger.html
logger:
  level: $LOG_LEVEL

# https://esphome.io/components/mqtt.html
mqtt:
  <<: !include ./mqtt_defaults.yaml
  birth_message:
  will_message:
  shutdown_message:

# https://esphome.io/components/i2c.html
i2c:

text_sensor:
  - <<: !include ./wifi_ip_addr_text_sensor.yaml

  - id: ota_keep_awake
    platform: mqtt_subscribe
    topic: info/maintenance/ota_keep_awake

sensor:
  - <<: !include ./wifi_rssi_sensor.yaml
  - <<: !include ./uptime_sensor.yaml

  - platform: sht3xd
    id: sht3xd_sensor
    address: 0x45
    update_interval: never

    temperature:
      name: $PREFIX Temperature
      retain: false

    humidity:
      name: $PREFIX Humidity
      retain: false

  - platform: bh1750
    id: bh1750_lux_sensor
    name: $PREFIX Lux
    address: 0x23
    measurement_time: 31
    update_interval: never
    retain: false

interval:
  - interval: 30s
    then:
      - if:
          condition:
            - mqtt.connected:
          then:
            - component.update: sht3xd_sensor
            - component.update: bh1750_lux_sensor
            - delay: 5s
            - if:
                condition:
                  lambda: return id(ota_keep_awake).state == "YES";
                then:
                  - logger.log:
                      format: OTA Keep Awake
                      level: INFO
                  - mqtt.publish:
                      topic: notify/maintenance/$NAME/ota_keep_awake
                      payload: $PREFIX - OTA Keep Awake
                      retain: yes
                else:
                  - mqtt.publish:
                      topic: notify/maintenance/$NAME/ota_keep_awake
                      payload: ""
                      retain: yes
                  - deep_sleep.enter:

deep_sleep:
  sleep_duration: $SLEEP_DURATION
