<<: !include ./wifi.yaml

# https://esphome.io/components/logger.html
logger:
  level: $LOG_LEVEL

# https://esphome.io/components/mqtt.html
mqtt:
  <<: !include ./mqtt_defaults.yaml
  birth_message:
  will_message:
  shutdown_message:

# https://esphome.io/components/i2c.html
i2c:

text_sensor:
  - <<: !include ./wifi_ip_addr_text_sensor.yaml

  - id: ota_keep_awake
    platform: mqtt_subscribe
    topic: info/maintenance/ota_keep_awake

binary_sensor:
  - name: $PREFIX Keep Awake
    platform: template
    lambda: return id(ota_keep_awake).state == "YES";

sensor:
  - <<: !include ./wifi_rssi_sensor.yaml
  - <<: !include ./uptime_sensor.yaml

  - platform: sht3xd
    id: sht3xd_sensor
    address: 0x45
    update_interval: never

    temperature:
      name: $PREFIX Temperature
      retain: false
      accuracy_decimals: 0
      expire_after: 1h

    humidity:
      name: $PREFIX Humidity
      retain: false
      accuracy_decimals: 0
      expire_after: 1h

  - platform: bh1750
    id: bh1750_lux_sensor
    name: $PREFIX Lux
    address: 0x23
    measurement_time: 31
    update_interval: never
    retain: false
    expire_after: 1h

interval:
  - interval: 10s
    then:
      - if:
          condition:
            - mqtt.connected:
          then:
            - component.update: sht3xd_sensor
            - component.update: bh1750_lux_sensor
            - delay: 5s
            - if:
                condition:
                  lambda: return id(ota_keep_awake).state == "YES";
                then:
                  - logger.log:
                      format: OTA Keep Awake
                      level: INFO
                else:
                  - deep_sleep.enter:

deep_sleep:
  sleep_duration: $UPDATE_INTERVAL
  run_duration: 15min
