esphome:
  name: $NAME
  platform: ESP8266
  board: d1_mini
  build_path: _builds/$NAME/

<<: !include ./wifi.yaml

mqtt:
  id: mqtt_client
  broker: !secret MQTT_BROKER
  username: !secret MQTT_USERNAME
  password: !secret MQTT_PASSWORD
  discovery_prefix: $MQTT_PREFIX/homeassistant
  topic_prefix: $MQTT_PREFIX/$NAME
  reboot_timeout: $REBOOT_TIMEOUT
  birth_message:
  will_message:
  shutdown_message:
  on_message:
    - topic: $MQTT_PREFIX/esphome_ota_keep_awake
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
        - switch.turn_on: ota_keep_awake
    - topic: $MQTT_PREFIX/esphome_ota_keep_awake
      payload: 'OFF'
      then:
        - switch.turn_off: ota_keep_awake

# https://esphome.io/components/i2c.html
i2c:

text_sensor:
  - <<: !include ./wifi_ip_addr_text_sensor.yaml

sensor:
  - <<: !include ./wifi_rssi_sensor.yaml
  - <<: !include ./uptime_sensor.yaml

  - platform: sht3xd
    id: sht3xd_sensor
    address: 0x45
    update_interval: never

    temperature:
      name: $PREFIX Temperature
      retain: false

    humidity:
      name: $PREFIX Humidity
      retain: false

  - platform: bh1750
    id: bh1750_lux_sensor
    name: $PREFIX Lux
    address: 0x23
    measurement_time: 31
    update_interval: never
    retain: false

switch:
  - id: ota_keep_awake
    platform: gpio
    pin: D4
    inverted: true
    restore_mode: ALWAYS_OFF

interval:
  - interval: 30s
    then:
      - if:
          condition:
            - mqtt.connected:
          then:
            - component.update: sht3xd_sensor
            - component.update: bh1750_lux_sensor
            - delay: 1s
            - if:
                condition:
                  - switch.is_on: ota_keep_awake
                then:
                  - logger.log:
                      format: "Deep sleep prevented"
                      level: INFO
                else:
                  - deep_sleep.enter: deep_sleep_1

deep_sleep:
  id: deep_sleep_1
  run_duration: 10min
  sleep_duration: $SLEEP_DURATION
